# Generated by Django 4.1.2 on 2022-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_specialization_user_specialization"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="specialization",),
        migrations.AddField(
            model_name="user",
            name="specialization",
            field=models.ManyToManyField(blank=True, to="account.specialization"),
        ),
    ]
