# Generated by Django 4.1.2 on 2022-10-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_specialization_user_specialization"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="specialization",),
        migrations.DeleteModel(name="Specialization",),
    ]
