# Generated by Django 4.1.2 on 2022-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apointment",
            name="speciality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
